# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160222_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isOwnedBy',
            field=models.BooleanField(default=False),
        ),
    ]
